inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '*.gemspec'
    - 'gemfiles/*'
    - 'vendor/bundle/**/*'
    - 'gemfiles/vendor/bundle/**/*'
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 90

Metrics/MethodLength:
  Enabled: true
  Max: 15

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
