AllCops:
  Exclude:
    - '*.gemspec'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'

Documentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Enabled: true
  Max: 90

Metrics/MethodLength:
  Enabled: true
  Max: 15

Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
