inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - '*.gemspec'
    - 'gemfiles/*'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'
    - 'gemfiles/vendor/bundle/**/*'

plugins: rubocop-rspec

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 90

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Enabled: true
  Max: 15

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
