inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
    - '*.gemspec'

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false
