AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
    - '*.gemspec'

Documentation:
    Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 90

Metrics/MethodLength:
  Enabled: true
  Max: 15

Style/ExtraSpacing:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
