AllCops:
  Exclude:
    - '*.gemspec'
    - 'gemfiles/*'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'
    - 'gemfiles/vendor/bundle/**/*'

require: rubocop-rspec

Documentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Enabled: true
  Max: 90

Metrics/MethodLength:
  Enabled: true
  Max: 15

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/integration/rails/action_mailer_spec.rb
    - spec/integration/rails/railtie_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
