name: Deploy to RubyGems
run-name: ${{ github.actor }} is publishing a new version

on:
  release:
    types: [published]

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build gem
        run: gem build loga.gemspec

      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          gem push loga-*.gem
